### ISSUE TITLE
© 1974, 1975, 1978, 1980 Bruce Springsteen (GMR) NOT handled right

### ISSUE THREAD

**Issue by vzell** [kellnerd/musicbrainz-bookmarklets#19] opened 2022-01-15 13:37 UTC
I found this copyright information on a Bruce Springsteen release:

© 1974, 1975, 1978, 1980 Bruce Springsteen (GMR)

See https://coverartarchive.org/release/5270ebbd-568e-473f-9b96-dc8d6cc7fde1/30980716343.jpg

GMR seems to stand for Global Music Rights https://globalmusicrights.com/catalog - https://musicbrainz.org/label/66463b28-e0ab-4693-aafa-35992119d3ca/relationships

It's not handled right now:

![image](https://user-images.githubusercontent.com/1648084/149623636-626c1bc0-7a90-438d-a961-d6cbf917949f.png)

**Comment by vzell** [comment] 2022-01-15 18:34
Also this one has problems:

℗ 2014, 2017, 2018, 2019 & 2020 Bruce Springsteen

![image](https://user-images.githubusercontent.com/1648084/149633683-cc84bdf1-170f-4284-a273-a135b643aceb.png)

**Comment by kellnerd** [comment] 2022-01-15 20:56
Multiple copyright years are currently not supported. Extracting them would be easy, but I am not sure what the script should do with them as this kind of copyright notice is very unspecific.
The different years usually refer to different tracks, so I don't think it would be appropriate to add multiple release relationships to have all of the dates?
Maybe I should just leave the date fields empty in such cases... (Not a problem as you can always force the parser to add/overwrite the date with a specific year by removing all the other years from the text input.)

In situations where it is unclear to which tracks a credit applies, I would usually try to research the exact details and add recording relationships according to my findings (or I would just skip the credit and leave it as an annotation). If you know for which recordings a copyright year applies, you can simply select their checkboxes and parse a notice which only contains the specific year.

> GMR seems to stand for Global Music Rights

This probably means that the "(GMR)" part can be safely dropped from the notice?

**Comment by kellnerd** [comment] 2022-01-15 21:56
Wait a moment, your first example is neither a phonographic copyright (where multiple years make sense) nor a release copyright (which refers to the artwork and should only have one year) as far as I can tell, these are **work copyrights** for the songs!
The rights society in brackets was the pointer, and now that I had a look at the scan, I can see that it is written directly under the "all songs written by" line.
I just confirmed that MB does not even support copyright relationships at work level, there are only publisher work-label or work-artist relationship types. That means the "(GMR)" suffix will probably stay a "won't fix" until MB adds support for these.
Maybe I should even display a warning if the parser finds a rights society?

**Comment by kellnerd** [comment] 2022-01-15 22:41
Support for the detection of multiple years has been added in 4136a26a28212698ebc894d9fc1f2166e02f3eeb (v2022.1.15), but these years will not be added as relationship dates for the reasons I outlined above.

**Comment by tigerman325** [comment] 2022-01-23 02:58
I usually add all the years if they are on the release like this. I always have just seen the dates as they are on the release, not really like a 1994-1996, etc. start date as it is with other relationships. But I can see how other editors might not like that. I've just been leaving one date than parsing and than just overwrite the date with the next date. Very quick and easy as your parser doesn't erase the whole text. Also, yes, I agree. Vzell's first example is for works. Would it be difficult to it also work for works like you do with the recordings? If the works are already on the page, you could just check box next to works and parse it like you can for recordings. But it'd probably try to add the copyright to the release as well (maybe a check box for works only on something?)

**Comment by kellnerd** [comment] 2022-01-24 15:44
I see two other sensible options what the parser could do with multiple years:

1. Add one relationship for each year to the release only, add one undated relationship to all selected recordings.
2. Additionally hide that option behind another key combo, maybe ALT+click.

Currently I'm in favor of option 2: Don't make it harder for editors who want to add these years and do not force others to add them. What do you think?

**Comment by tigerman325** [comment] 2022-01-25 04:54
I like option 2 for the same reasons you just said.

**Comment by vzell** [comment] 2022-01-25 06:40
+1 for option 2

**Comment by kellnerd** [comment] 2022-01-25 11:07
Support for optionally creating one release relationship per copyright year has been added in 3ddf710e2f082fb0c40c1672fedd63a975325199 (released as v2022.1.25). I'm also closing this issue as the feasible parts have been implemented now and work copyrights are not supported in MB so far.

**Closed by kellnerd** 2022-01-25 11:07 UTC
Labels: bug, enhancement, copyright
